### ISSUE TITLE
完美第一弹

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/RecyclerViewAdapter#1]
1. 分割线现在支持了Drawable,是否能支持传一个颜色值，传什么值就显示什么颜色的分割线

**Comment by LwkCoder** [comment]
@hegelsu  目前暂时没有这个打算，最近比较忙，如果急需还请自己先实现哈

**Comment by hegelsu** [comment]
不急，只是提个建议。

**Comment by LwkCoder** [comment]
@hegelsu 今天有空，把你的建议实现了，你看看1.2.9版本的

**Comment by hegelsu** [comment]
![1](https://user-images.githubusercontent.com/6879123/34715375-62704718-f567-11e7-9b1b-d6cfae4d5321.png)
1. 颜色的没有问题了，另外想问下，就是每块section第一个item的上面和最后一个item的下面其实不要这个分隔线才好看一点，不知道如何去处理？
2. 如果想仿下iOS的效果怎么办，ios的分隔线可以设置一个左边距的距离

**Comment by LwkCoder** [comment]
@hegelsu 
①section也是属于RecyclerView中的子View，但分割线不是设置在Adapter中的，ItemDecrotaion中无法所以无法区分哪一行是section，所以建议在设置section背景的时候改为和分割线一样的颜色就看不出来了;
②这种情况的话其实不建议你用ItemDecoration了，不如直接在每一个item的布局里手动添加一个View来充当分割线，原理同上，当然我后续版本可以考虑在分割线中新增一个设置padding的方法。

**Comment by hegelsu** [comment]
好的，谢谢。
