### ISSUE TITLE
加载更多

### ISSUE THREAD

**Issue by jxdwinter** [Vanish136/RecyclerViewAdapter#10]
adapter设置了loadmore=true，进入activity以后自动加载了第一次数据之后，滑动到最下面以后，正在加载不会触发任何方法了。
请大佬帮忙看一下，谢谢!
<img width="828" alt="Screen Shot 2021-03-24 at 11 23 16" src="https://user-images.githubusercontent.com/1195524/112249833-6525f680-8c93-11eb-8d7f-26ba1dbf49ab.png">

<img width="500" alt="Screen Shot 2021-03-24 at 11 23 38" src="https://user-images.githubusercontent.com/1195524/112249835-68b97d80-8c93-11eb-93a5-68119258d92f.png">

<img width="466" alt="Screen Shot 2021-03-24 at 11 26 10" src="https://user-images.githubusercontent.com/1195524/112250074-c8b02400-8c93-11eb-99ea-f18ecdaa12b4.png">

另外设置了loadmore=true以后，进入activity之后会自动加载数据吗？

**Comment by LwkCoder** [comment]
首先回答你第二个问题，如果你在初始化Activity的时候就设置了enableLoadMore(true)，那么进入Activity后会自动触发一次加载数据。

再看你的代码中，第一页的数据是用的refreshDatas(dataSource)，这里用错了，这个方法是给下拉刷新后用的，内部不会重设自动加载的状态，而自动加载后的数据传入方法对应的是notifyLoadMoreSuccess()、notifyLoadMoreFail()等方法，这些方法会在内部重设自动加载的状态；

我看了下你的代码，应该不需要判断加载后是第几页，可以尝试下精简为
```
//第二个参数代表判断是否还能继续触发加载更多
adapter.notifyLoadMoreSuccess(dataSource,dataSource.size()>=20);
pageNo++;
```

**Comment by jxdwinter** [comment]
@Vanish136 感谢回复和精简建议，非常方便的Adapter，按照您说的我做了相应的修改，在初始化Activity的时候就设置enableLoadMore(true)，但是第一次加载数据之后，整个页面处于list的最底部了。请问是我哪里写的不对吗？谢谢！

<img width="482" alt="Screen Shot 2021-03-24 at 14 08 42" src="https://user-images.githubusercontent.com/1195524/112263616-90681000-8caa-11eb-98db-30b17e0e6173.png">

**Comment by jxdwinter** [comment]
我之所以用refreshDatas这个方法来加载第一次请求的数据，也是因为直接用notifyLoadMoreSuccess的话，会直接到整个recyclerView的最底部，如上图所示。

**Comment by LwkCoder** [comment]
方便贴出相关代码和布局吗？

**Comment by jxdwinter** [comment]
@Vanish136 刚弄Android不久，可能有些地方写的不对，请您帮忙看下，谢谢！

![Screen Shot 2021-03-24 at 16 44 26](https://user-images.githubusercontent.com/1195524/112280749-4e49c900-8cc0-11eb-8888-0697464e4fe7.png)

**Comment by jxdwinter** [comment]
布局相关代码:

<img width="509" alt="Screen Shot 2021-03-24 at 16 55 44" src="https://user-images.githubusercontent.com/1195524/112282466-1d6a9380-8cc2-11eb-902f-4502dd0283a8.png">

**Comment by LwkCoder** [comment]
针对你这个场景，我觉得最简单粗暴的办法就是在数据请求完成后，判断当前adapter中的数据源数量是否为0，如果为0则用refreshData()，不为0再用notifyLoadMoreSuccess()。
因为notifyLoadMoreSuccess()内部调用的是adapter的notifyItemRangeInserted(int position,int count)，这个方法属于局部刷新，内部机制里需要记住刷新前的位置以便刷新后还原位置，所以我猜测（仅仅是猜测）当adapter数据源为0时则高度尚未充满一屏，刷新前记住的位置就是底部，刷新后就会还原到底部，而refreshDatas()不是局部刷新，而是全部替换数据源的全量刷新，不存在这样的问题。

所以在加载数据的地方建议修改如下：
```
if (mAdapter.getDataSize() == 0)
{
        mAdapter.refreshDatas(dataSource);
        if (dataSource.size() < 20)
        {
              mAdapter.notifyLoadMoreHasNoMoreData();
        }
} else
{
       mAdapter.notifyLoadMoreSuccess(dataSource, dataSource.size() >= 20);
       //这里只需要上面一行代码就行了
       //你截图里boolean hasMoreData = dataSoruce.size()>=20?true:false是多此一举，编译器给这行代码标注黄色就是提醒你可以简化
}
```

**Comment by jxdwinter** [comment]
@Vanish136 这样的话，加载更多就又不会执行了，仅仅是一个“正在加载”显示，没有触发方法。
数据是可以撑满一屏的。

**Comment by LwkCoder** [comment]
抱歉，盲敲的，搞忘了，试试这样
```
if (mAdapter.getDataSize() == 0)
{
        mAdapter.refreshDatas(dataSource);
        mAdapter.notifyLoadMoreSuccess(0, dataSource.size() >= 20);
} else
{
       mAdapter.notifyLoadMoreSuccess(dataSource, dataSource.size() >= 20);
}
```

**Comment by jxdwinter** [comment]
谢谢大佬的回复！我在研究下您的源码！
boolean hasMoreData = dataSoruce.size()>=20?true:false 我这样写的原因是要根据boolean值来判断是否需要pageNo++

**Comment by jxdwinter** [comment]
boolean hasMoreData = dataSoruce.size()>=20 😂 哈哈，写错了

**Comment by jxdwinter** [comment]
但是我加载的数据是可以撑满一屏的，感谢大佬帮助解决问题！
