### ISSUE TITLE
gradle集成报错

### ISSUE THREAD

**Issue by jxdwinter** [Vanish136/RecyclerViewAdapter#11]
Android Studio : 4.2.2
gradle : 4.2.2

`Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.lwkandroid.library:rcvadapter:last-version.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

**Comment by jxdwinter** [comment]
<img width="591" alt="error" src="https://user-images.githubusercontent.com/1195524/126096578-e04dbfa0-d89e-497c-93ab-d2439e4453bc.png">

**Comment by LwkCoder** [comment]
last-version换成最新的版本号
https://github.com/Vanish136/RecyclerViewAdapter/releases
