### ISSUE TITLE
Header和Footer没有全宽

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/RecyclerViewAdapter#2]
`<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
          android:layout_width="match_parent"
          android:layout_height="60dp"
          android:background="@android:color/holo_green_dark"
          android:gravity="center"
          android:text="HeaderView"
          android:textSize="18sp">
</TextView>`
![1](https://user-images.githubusercontent.com/6879123/34954407-4d50cc10-fa5b-11e7-903f-867a5cfddda6.png)

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
  <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
    <android.support.v7.widget.RecyclerView
       android:id="@+id/dataLV"
       android:layout_width="match_parent"
       android:layout_height="match_parent" />
    <com.lwkandroid.rcvadapter.ui.RcvStickyLayout
              android:id="@+id/stickyLayout"
              android:layout_width="match_parent"
              android:layout_height="wrap_content" />
  </FrameLayout>
  <com.gjiazhe.wavesidebar.WaveSideBar
        android:id="@+id/side_bar"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingRight="8dp"
        app:sidebar_position="right"
        app:sidebar_max_offset="80dp"
        app:sidebar_lazy_respond="true"
        app:sidebar_text_color="#8D6E63" />
</RelativeLayout>`

**Comment by LwkCoder** [comment]
@hegelsu 
你在代码中如何初始化HeaderView的？
请参考demo中的样式：
 View headerView = getLayoutInflater().inflate(R.layout.layout_headview, (ViewGroup) findViewById(android.R.id.content), false);

**Comment by hegelsu** [comment]
我是在Fragment里的CreateView里添加的，语法可能不一样，意思你应该可以看得明白：
`public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            View view = base.OnCreateView(inflater, container, savedInstanceState);
            mAdapter.AddHeaderView(inflater.Inflate(Resource.Layout.fragmentforthheader, view.FindViewById<ViewGroup>(Android.Resource.Id.Content), false));
            mAdapter.AddFooterView(inflater.Inflate(Resource.Layout.fragmentforthfooter, view.FindViewById<ViewGroup>(Android.Resource.Id.Content), false));
            return view;
        }`

不知道和在Acitivity里处理是不是有什么不同

**Comment by LwkCoder** [comment]
@hegelsu 
你把view.FindViewById<ViewGroup>(Android.Resource.Id.Content)改为getActivity.findViewById试试，如果还不行的话，那手动设置下HeaderView的布局参数吧，如下：
ViewGroup.LayoutParams params = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);
headerView.setLayoutParams(params);

**Comment by hegelsu** [comment]
是的，从Activity里findView即可解决。
