### ISSUE TITLE
看后期是否可以规划不同类型的headerView和footView

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/RecyclerViewAdapter#3]
![1](https://user-images.githubusercontent.com/6879123/35493571-62e0058e-04ef-11e8-9e29-d51d2032a0e2.png)
如图

**Comment by LwkCoder** [comment]
@hegelsu 没看懂你的意思？是需要不同类型的section？

**Comment by hegelsu** [comment]
1. 是的，需要不同布局Layout的Section
2. 另外关于Section的分隔线，我记得有一个可以参考：
https://github.com/bingoogolapple/BGABaseAdapter-Android

**Comment by LwkCoder** [comment]
@hegelsu 之前在设计的时候并没有考虑多种Section的情况，导致现在这块改起来可能有点多，年底了工作比较忙，而且在准备其他的项目，所以暂时无法抽出空来做这个了，如果有其他三方库可以实现，你可以先用来替代，不好意思啦

**Comment by hegelsu** [comment]
不急，我现在也暂时不需要，目前是通过这两个Header共用layout的，判断不同的类型来隐藏显示控件达到效果，多样式Header的库以前用过，只是在想如果有一个通用的当然最好，后面有功夫再说。
