### ISSUE TITLE
"加载更多" 可能有问题

### ISSUE THREAD

**Issue by VcotyQin** [Vanish136/RecyclerViewAdapter#4]
数据都已经加载完了，但还是会调用setBeforeLoadingUI() <本应为setNoMoreDataUI() > 
但是又向上滑很长一段距离后又向下滑就调用setNoMoreDataUI()

**Comment by Vanish136** [comment]
适配器本身无法知道是否还有下一页数据，所以这个逻辑需要开发人员在外部判断好，将结论告诉适配器。
在加载完数据后成后配合适配器的如下方法来设置数据：
`
mAdapter.refreshData(List<T> list)；
mAdapter.notifyLoadMoreSuccess(List<T> list, boolean hasMoreData);
mAdapter.notifyLoadMoreFail();
mAdapter.notifyLoadMoreHasNoMoreData();
`

当然， 你最好看一下我今天针对你这个问题更新的demo示例，这样就能搞清楚下拉刷新和上拉加载如何配合。
[RefreshActivity](https://github.com/Vanish136/RecyclerViewAdapter/blob/master/app/src/main/java/com/lwksample/rcvadapter/refresh/RefreshActivity.java)

**Comment by VcotyQin** [comment]
好了，非常感谢！
