### ISSUE TITLE
License

### ISSUE THREAD

**Issue by VcotyQin** [Vanish136/RecyclerViewAdapter#5]
许可证呢？

**Comment by Vanish136** [comment]
@VcotyQin 谢谢提醒，已添加

**Comment by VcotyQin** [comment]
你好像名字没填

**Comment by Vanish136** [comment]
@VcotyQin 
在哪里填？这个是必须的吗...不是加上LICENSE就行了。。？
我看了下retrofit的LICENSE也是一样的...
https://github.com/square/retrofit/blob/master/LICENSE.txt

**Comment by Vanish136** [comment]
@VcotyQin 
既然你这么严谨，那我还是把名字加上好了，谢谢你

**Comment by VcotyQin** [comment]
讲真，你这玩意儿是真的方便！😂
