### ISSUE TITLE
findFirstCompletelyVisibleItemPosition方法的bug

### ISSUE THREAD

**Issue by FeverCombo3** [Vanish136/RecyclerViewAdapter#8]
当Item的长度比较长的时候，比如界面上有两个Item，都显示不全，findFirstCompletelyVisibleItemPosition这个方法就会返回-1，头部的吸顶就消失了。

**Comment by FeverCombo3** [comment]
解决方法可以让findFirstCompletelyVisibleItemPosition == -1的判断条件再严谨一点

**Comment by LwkCoder** [comment]
@FeverCombo3 1.3.8版本针对这种情况修复了，你试试看
