### ISSUE TITLE
能不能实现上拉过程自动加载，不显示任何提示

### ISSUE THREAD

**Issue by hiliving** [Vanish136/RecyclerViewAdapter#9]
给用户的感觉就是一次性就加载了所有数据，可以一直上滑，滑动过程不停的去加载更多，无痕更新列表

**Comment by LwkCoder** [comment]
如果是不显示提示，你可以自定义一个类继承自`RcvBaseLoadMoreView`，布局内就给一个1px高度的View，其余方法都不实现，然后设置` mAdapter.setLoadMoreLayout(你自定义的类对象);`，这样拉到底部的时候就没有任何提示。
但是实际使用的过程中，首先要知道网络请求是耗时的，无法保证请求结果能瞬间返回，当用户拉到底部时，从网络请求到返回结果的之前这段时间列表是拉不动的，然后数据返回后再更新了列表，又可以继续往下拉，从用户角度上看像是卡顿了一下，体验并不好，而且如果网络请求是失败的，那么没有任何提示给用户，也是很不好的体验，所以你描述的情况有点过于理想化了。

**Comment by hiliving** [comment]
是这样，不一定拉到底部才开始加载更多，也许离底部还有一些距离，比如还差4条到底部，这个时候立刻加载更多，这样真正到达底部时，新的数据已经准备好了，就可以继续拉，给人感觉就是无痕加载，很流畅，也没有卡顿，你可以参考 下厨房 app，里面的菜谱列表就是这样的 @Vanish136

**Comment by LwkCoder** [comment]
@hiliving 这种情况很好解决啊，就需要针对RecyclerView的滑动进行监听，即:
```
mRecyclerView.addOnScrollListener(new OnScrollListener()
        {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState)
            {
                super.onScrollStateChanged(recyclerView, newState);
                //滑动状态改变回调
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy)
            {
                super.onScrolled(recyclerView, dx, dy);
                //滑动过程回调
            }
        });
```
在这个回调里进行你需要的逻辑处理，判断当前最后一个显示的item位置。
当然还是那句话，即使你提前N条就开始加载下一页数据了，仍然可能存在网络很不好的情况导致滑动到底部了数据还没返回回来，此时也没有任何提示给用户，个人认为体验上还是不太妥当，你自己参考下吧。
